/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.WorkerRole;

import Business.Area.Area;
import Business.Employee.Worker;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Entities.LeaveRequest;
import Business.Enterprise.Entities.ManufactureTask;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keweiji
 */
public class WorkerLeavesManagePanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkerLeavePanel
     */
    private JPanel userProcessContainer;
    private Worker worker;

    public WorkerLeavesManagePanel(JPanel userProcessContainer, Worker worker) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.worker = worker;
        populatetable();
        this.setOpaque(false);
    }

    public void populatetable() {
        DefaultTableModel model = (DefaultTableModel) leavesTable1.getModel();

        model.setRowCount(0);

        for (LeaveRequest leavequest : worker.getLeaverequestsList()) {
            Object[] row = new Object[3];
            row[0] = leavequest.getRequestid();
            row[1] = leavequest.getReason().length() > 20 ? leavequest.getReason().substring(0, 20) : leavequest.getReason();
            row[2] = leavequest.isApproved() ? "Approved" : "Not approved yet";

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        daysjTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reasonjTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        leavesTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();
        submitjButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("Leaves days:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));
        add(daysjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 110, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel2.setText("Reason:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 300, 70, -1));

        reasonjTextArea1.setColumns(20);
        reasonjTextArea1.setRows(5);
        jScrollPane1.setViewportView(reasonjTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 390, 70));

        leavesTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "request id", "brief", "status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(leavesTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 490, 110));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setText("History");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Apply for a new workoff");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        backjButton1.setText("back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        submitjButton2.setText("Submit");
        submitjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButton2ActionPerformed(evt);
            }
        });
        add(submitjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void submitjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButton2ActionPerformed
        // TODO add your handling code here:
        int days = Integer.parseInt(daysjTextField1.getText());
        String reason = reasonjTextArea1.getText();
        worker.setWorkable(false);
        

//        for (int i = worker.getTaskList().size()-1; i >= 0; i--) {
//            ManufactureTask task = worker.getTaskList().get(i);
//            if (task.getCompleted() == false) {
//                task.getMenTakePartIn().remove(worker);
//                worker.getTaskList().remove(task);
//                break;
//            }
//        }
        worker.getLeaverequestsList().add(new LeaveRequest(days, reason));
        populatetable();
    }//GEN-LAST:event_submitjButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JTextField daysjTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable leavesTable1;
    private javax.swing.JTextArea reasonjTextArea1;
    private javax.swing.JButton submitjButton2;
    // End of variables declaration//GEN-END:variables
}
