/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.BuyOrganizationDirectorWorkArea;

import Business.Employee.Buyer;
import Business.Employee.Employee;
import Business.Enterprise.Entities.Buyorder;
import Business.Enterprise.Entities.Material;
import Business.Enterprise.ManufactureEnterprise;
import Business.Organization.Organization;
import Business.Organization.PurchaseOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keweiji
 */
public class BuyOrderAssignsJPanel extends javax.swing.JFrame {

    /**
     * Creates new form BuyOrderAssignsJPanel
     */
    private ManufactureEnterprise manufactureEnterprise;
    private JPanel userProcessContainer;
    private PurchaseOrganization purchaseOrganization;
//    private Buyorder buyorder;
    private HashMap<Material,Integer> materialsHashMap;
//    private UserAccount account;

    public BuyOrderAssignsJPanel(JPanel userProcessContainer, Organization organization, ManufactureEnterprise manufactureEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.manufactureEnterprise = manufactureEnterprise;
        this.purchaseOrganization = (PurchaseOrganization) organization;
        this.materialsHashMap = new HashMap<Material,Integer>();
//        this.buyorder = new Buyorder();
//        this.account = account;
        populatebox();
        populatetables();
    }

//    private BuyOrderAssignsJPanel() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    public void populatebox() {
        BuyerjComboBox.removeAllItems();
        for (Employee employee : this.purchaseOrganization.getEmployeeDirectory().getEmployeeList()) {
            if (employee instanceof Buyer) {
                BuyerjComboBox.addItem(employee);
            }
        }
    }

    public void populatetables() {
        DefaultTableModel model = (DefaultTableModel) materialjTable1.getModel();
        model.setRowCount(0);
        for (Material material : this.manufactureEnterprise.getTodomaterialHashMap().keySet()) {
            Object[] row = new Object[2];
            row[0] = material;
            row[1] = this.manufactureEnterprise.getTodomaterialHashMap().get(material);
            model.addRow(row);
        }

        DefaultTableModel model2 = (DefaultTableModel) OrderTable2.getModel();
        model.setRowCount(0);
        for (Material material : this.materialsHashMap.keySet()) {
//            if(employee instanceof  Buyer){
            Object[] row = new Object[2];
            row[0] = material;
            row[1] =  this.materialsHashMap.get(material);
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        materialjTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderTable2 = new javax.swing.JTable();
        createBt = new javax.swing.JButton();
        add2orderjButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BuyerjComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        materialjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Material", "Amounts"
            }
        ));
        jScrollPane1.setViewportView(materialjTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 140));

        OrderTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Material", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(OrderTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 100));

        createBt.setText("Create Order ");
        createBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtActionPerformed(evt);
            }
        });
        getContentPane().add(createBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        add2orderjButton2.setText("Add to BuyOrder");
        add2orderjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2orderjButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(add2orderjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel1.setText("Purchase order Items:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 206, 160, 30));

        BuyerjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BuyerjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyerjComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(BuyerjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 130, -1));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtActionPerformed
        Buyer buyer = (Buyer)BuyerjComboBox.getSelectedItem();
        Buyorder buyorder = new Buyorder();
        for(Material material: this.materialsHashMap.keySet()){
            buyorder.getMaterials().put(material, this.materialsHashMap.get(material));
        }
        this.materialsHashMap.clear();
        buyer.getBuyerorders().add(buyorder);
        populatetables();
    }//GEN-LAST:event_createBtActionPerformed

    private void add2orderjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2orderjButton2ActionPerformed
        // TODO add your handling code here:
        try {
            int materialindex = materialjTable1.getSelectedRow();
            Material material =(Material) materialjTable1.getValueAt(materialindex, 0);
            int amounts = (int) materialjTable1.getValueAt(materialindex, 1);
            this.materialsHashMap.put(material, amounts);
            this.manufactureEnterprise.getTodomaterialHashMap().remove(material);
            populatetables();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select a material item to add");
        }
    }//GEN-LAST:event_add2orderjButton2ActionPerformed

    private void BuyerjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyerjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuyerjComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BuyOrderAssignsJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BuyOrderAssignsJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BuyOrderAssignsJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BuyOrderAssignsJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BuyOrderAssignsJPanel().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BuyerjComboBox;
    private javax.swing.JTable OrderTable2;
    private javax.swing.JButton add2orderjButton2;
    private javax.swing.JButton createBt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable materialjTable1;
    // End of variables declaration//GEN-END:variables
}
