/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.BuyerWorkArea;

import Business.Enterprise.Enterprise;
import Business.Enterprise.ManufactureEnterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Organization.PurchaseOrganization;
import Business.UserAccount.UserAccount;
import Interface.BuyOrganizationDirectorWorkArea.BuyOrderAssignsJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JPanel;

/**
 *
 * @author keweiji
 */
public class BuyerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
//    private PurchaseOrganization purchaseOrganization;
    private ManufactureEnterprise manufactureEnterprise;
    private HashMap<ManufactureEnterprise, String> manufactureEnterprises;
    private HashMap<SupplierEnterprise, String> supplierEnterprises;

    public BuyerWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,Enterprise enterprise,
            HashMap<ManufactureEnterprise, String> manufactureEnterprises, HashMap<SupplierEnterprise, String> supplierEnterprises) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.manufactureEnterprise = (ManufactureEnterprise)enterprise;
        this.manufactureEnterprises = manufactureEnterprises;
        this.supplierEnterprises = supplierEnterprises;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Excute Task");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 230, 45));

        jButton2.setText(" Tasks history");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 230, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                        userProcessContainer.add("manageOrganizationJPanel", new BuyOrderAssignsJPanel(userProcessContainer, manufactureEnterprise, manufactureEnterprise));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
