/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManufactureDirectorWorkArea;

import Business.Enterprise.Enterprise;
import Business.Enterprise.ManufactureEnterprise;
import Business.Enterprise.SalesEnterprise;
import Business.Organization.ProductOrganization;
import Interface.ManufactureDirectorWorkArea.*;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author keweiji
 */
public class ManufactureDirectorWorkAreaJPanel extends javax.swing.JPanel {
       private JPanel userProcessContainer;
   private ManufactureEnterprise manufactureEnterprise;
   private ProductOrganization manufactureOrganization;

    /**
     * Creates new form ManufactureDirectorWorkAreaJPanel
     */
    public ManufactureDirectorWorkAreaJPanel(JPanel userProcessContainer,ProductOrganization manufactureOrganization,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.manufactureEnterprise=(ManufactureEnterprise)enterprise;
        this.manufactureOrganization= manufactureOrganization;
        System.out.println(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignmentjButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        calculationjButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignmentjButton1.setText("Assignment Placement");
        assignmentjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentjButton1ActionPerformed(evt);
            }
        });
        add(assignmentjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 122, 234, 40));

        jButton1.setText("《back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 258, -1, -1));

        jButton2.setText("approve leave off ");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 205, 220, -1));

        calculationjButton3.setText("Material Calculattion");
        calculationjButton3.setEnabled(false);
        calculationjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationjButton3ActionPerformed(evt);
            }
        });
        add(calculationjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 40, 240, -1));

        jButton4.setText("Create Manufacture Task");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 81, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignmentjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentjButton1ActionPerformed
        // TODO add your handling code here:
//        if (this.enterprise instanceof SalesEnterprise) {
//            SalesEnterprise maincompany = (SalesEnterprise) enterprise;
//            ProductOrganizationAssignmentPlacementPanel mainCompanyAssignmentPlacementPanel = new ProductOrganizationAssignmentPlacementPanel(userProcessContainer, maincompany);
//            userProcessContainer.add("manageOrganizationJPanel", mainCompanyAssignmentPlacementPanel);
//            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//            layout.next(userProcessContainer);
//        }
        MainCompanyManufactureTaskAssignPanel mainCompanyManufactureTaskAssignPanel = new MainCompanyManufactureTaskAssignPanel(userProcessContainer, manufactureEnterprise);

        userProcessContainer.add("manageOrganizationJPanel", mainCompanyManufactureTaskAssignPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_assignmentjButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
            userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void calculationjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculationjButton3ActionPerformed
        // TODO add your handling code here:
        BuyingOrderCalculattionPanel buyingOrderCalculattionPanel = new BuyingOrderCalculattionPanel(userProcessContainer, manufactureEnterprise);
//        BuyingOrderCalculattionPanel buyingOrderCalculattionPanel = new BuyingOrderCalculattionPanel(userProcessContainer, salesAndBuysOrganization, (SalesEnterprise) enterprise);
        userProcessContainer.add("buyingOrderCalculattionPanel", buyingOrderCalculattionPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_calculationjButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CreateManufactureTask createManufactureTask = new CreateManufactureTask(userProcessContainer, manufactureEnterprise);
        userProcessContainer.add("buyingOrderCalculattionPanel", createManufactureTask);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignmentjButton1;
    private javax.swing.JButton calculationjButton3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
