/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SalesmanWorkarea;

import Business.Area.Area;
import Business.Employee.Customer;
import Business.Employee.Salesman;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Entities.MaterialDirectory;
import Business.Enterprise.Entities.Product;
import Business.Organization.SalesOrganization;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Enterprise.Entities.SalesOrder;
import Business.Enterprise.SalesEnterprise;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author amber
 */
public class CreatAOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatAOrder
     */
    private JPanel userProcessContainer;
    private SalesOrganization organization;
    private SalesEnterprise salesEnterprise;
    private UserAccount userAccount;
    private ArrayList<Area> arealist;
    private HashMap<Product, Integer> itemsHashMap;
//    private SalesOrder salesOrder;

    public CreatAOrderJPanel(JPanel userProcessContainer, UserAccount account, SalesOrganization organization, Enterprise enterprise, ArrayList<Area> arealist) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.salesEnterprise = (SalesEnterprise) enterprise;
        this.userAccount = account;
        this.arealist = arealist;
        this.itemsHashMap = new HashMap<Product, Integer>();
//        this.salesOrder = new SalesOrder();

        populateTable();
        populatebox();
        
    }

    public void populatebox() {
        CustomerjComboBox.removeAllItems();
        for (Customer customer : this.salesEnterprise.getCustomerDirectory().getCustomerDict()) {
            CustomerjComboBox.addItem(customer);
        }
        AreajComboBox1.removeAllItems();
        for (Area area : this.arealist) {
            AreajComboBox1.addItem(area);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        itemjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PricejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        productjSpinner = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productjTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        CustomerjComboBox = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AreajComboBox1 = new javax.swing.JComboBox();

        itemjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Quantity", "Total Price"
            }
        ));
        jScrollPane1.setViewportView(itemjTable);

        jLabel1.setText("Create A Order");

        jLabel5.setText("Sales Price");

        PricejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PricejTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Quantity");

        jButton3.setText("Add item");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        productjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Target Price"
            }
        ));
        jScrollPane2.setViewportView(productjTable);

        jButton4.setText("Create");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Remove");

        CustomerjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CustomerjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerjComboBoxActionPerformed(evt);
            }
        });

        jButton6.setText("<<back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setText("Customer Name :");

        jLabel4.setText("Delivery Destination:");

        AreajComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AreajComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreajComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustomerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AreajComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(PricejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(productjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(AreajComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PricejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(productjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(320, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Customer customer = (Customer) CustomerjComboBox.getSelectedItem();
//        salesOrder.setCustomer(customer);
        SalesOrder salesorder = ((Salesman) userAccount.getEmployee()).getSalesOrderDictory().addSalesOrder();
        salesorder.setCustomer(customer);
        salesorder.setDestinationState(((Area)AreajComboBox1.getSelectedItem()).getName());
        for (Product product : this.itemsHashMap.keySet()) {
            salesorder.getItems().put(product, this.itemsHashMap.get(product));
        }
        this.itemsHashMap.clear();
       salesEnterprise.getSalesOrdersDirectoryArrayList().add(salesorder);
        
        JOptionPane.showMessageDialog(null, "Create sales order successfully !");
        populateTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CustomerjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerjComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CustomerjComboBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // TODO add your handling code here:
        try {
                    int index = productjTable.getSelectedRow();
        Product product = (Product) productjTable.getValueAt(index, 1);
        product.setSalesprice(Integer.parseInt(PricejTextField.getText()));
        System.out.println(productjSpinner.getValue().toString());
        this.itemsHashMap.put(product, Integer.parseInt(productjSpinner.getValue().toString()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select a product and input the price and anmouts");
            return;
        }

        
        DefaultTableModel model = (DefaultTableModel) itemjTable.getModel();

//        model.setRowCount(0);
        for (Product product2 : itemsHashMap.keySet()) {
            Object[] row = new Object[4];
            row[0] = product2.getID();
            row[1] = product2.getNameString();
            row[2] = itemsHashMap.get(product2);
            row[3] = itemsHashMap.get(product2) * product2.getSalesprice();
            model.addRow(row);
        }

//        PricejTextField.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void AreajComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreajComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreajComboBox1ActionPerformed

    private void PricejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PricejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PricejTextFieldActionPerformed
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) productjTable.getModel();
        
        model.setRowCount(0);
        if (salesEnterprise.getProductDictory().getProductsDict().isEmpty()) {
            MaterialDirectory materialDirectory = new MaterialDirectory();
            Product product = new Product(Product.ProductType.Bike, materialDirectory);
            salesEnterprise.getProductDictory().getProductsDict().add(product);
        }
        for (Product p : salesEnterprise.getProductDictory().getProductsDict()) {
            Object[] row = new Object[3];
            row[0] = p.getID();
            row[1] = p;
            row[2] = p.getPrice();
            model.addRow(row);
        }
        
        DefaultTableModel model2 = (DefaultTableModel) itemjTable.getModel();
        model2.setRowCount(0);
        for (Product product2 : itemsHashMap.keySet()) {
            Object[] row = new Object[4];
            row[0] = product2.getID();
            row[1] = product2.getNameString();
            row[2] = itemsHashMap.get(product2);
            row[3] = itemsHashMap.get(product2) * product2.getSalesprice();
            model2.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AreajComboBox1;
    private javax.swing.JComboBox CustomerjComboBox;
    private javax.swing.JTextField PricejTextField;
    private javax.swing.JTable itemjTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner productjSpinner;
    private javax.swing.JTable productjTable;
    // End of variables declaration//GEN-END:variables
}
