/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ProductionDirectorWorkArea;

import Business.Employee.Worker;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Entities.WorkLine;
import Business.Enterprise.ManufactureEnterprise;
import Business.Enterprise.SalesEnterprise;
import Business.Organization.ProductOrganization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keweiji
 */
public class ProductionDirectorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ManufactureEnterprise manufactureEnterprise;
    private ProductOrganization manufactureOrganization;

    /**
     * Creates new form ManufactureDirectorWorkAreaJPanel
     */
    public ProductionDirectorWorkAreaJPanel(JPanel userProcessContainer, ProductOrganization manufactureOrganization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.manufactureEnterprise = (ManufactureEnterprise) enterprise;
        this.manufactureOrganization = manufactureOrganization;
        System.out.println(enterprise.getName());
        populatetables();
    }

    public void populatetables() {

        for (int i = 0; i <= 2; i++) {
            if (i == 0) {
                DefaultTableModel model = (DefaultTableModel) jTable0.getModel();
                model.setRowCount(0);
                WorkLine workline = manufactureEnterprise.getFactory().getWorklines().get(i);
                for (Worker worker : workline.getWorkersArrayList()) {
                    Object[] row = new Object[2];
                    row[0] = String.valueOf(worker.getId());
                    row[1] = worker.getName();
                    model.addRow(row);
                }
                line1number.setText("Vacant Place:" + (workline.getCapcity() - workline.getWorkersArrayList().size()));

            } else if (i == 1) {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                WorkLine workline = manufactureEnterprise.getFactory().getWorklines().get(i);
                for (Worker worker : workline.getWorkersArrayList()) {
                    Object[] row = new Object[2];
                    row[0] = String.valueOf(worker.getId());
                    row[1] = worker.getName();
                    model.addRow(row);
                }
                line2number.setText("Vacant Place:" + (workline.getCapcity() - workline.getWorkersArrayList().size()));
            } else if (i == 2) {
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setRowCount(0);
                WorkLine workline = manufactureEnterprise.getFactory().getWorklines().get(i);
                for (Worker worker : workline.getWorkersArrayList()) {
                    Object[] row = new Object[2];
                    row[0] = String.valueOf(worker.getId());
                    row[1] = worker.getName();
                    model.addRow(row);
                }
                line3number.setText("Vacant Place:" + (workline.getCapcity() - workline.getWorkersArrayList().size()));

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignmentjButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable0 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        line3number = new javax.swing.JLabel();
        line1number = new javax.swing.JLabel();
        line2number = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignmentjButton1.setText("Assignment Placement");
        assignmentjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentjButton1ActionPerformed(evt);
            }
        });
        add(assignmentjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 234, 30));

        jButton2.setText("Manage leave offs");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 240, -1));

        jButton4.setText("Create Manufacture Task");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 240, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Factory Detail"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "worker name", "Task id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 280, 70));

        jLabel1.setText("Line 3");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel2.setText("Line 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel3.setText("Line 2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jTable0.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "worker name", "Task id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable0);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 280, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "worker name", "Task id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 280, 70));

        line3number.setText("Vacant place: xx");
        jPanel1.add(line3number, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 30));

        line1number.setText("Vacant place: xx");
        jPanel1.add(line1number, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 30));

        line2number.setText("Vacant place: xx");
        jPanel1.add(line2number, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 680, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void assignmentjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentjButton1ActionPerformed
        // TODO add your handling code here:
//        if (this.enterprise instanceof SalesEnterprise) {
//            SalesEnterprise maincompany = (SalesEnterprise) enterprise;
//            ProductOrganizationAssignmentPlacementPanel mainCompanyAssignmentPlacementPanel = new ProductOrganizationAssignmentPlacementPanel(userProcessContainer, maincompany);
//            userProcessContainer.add("manageOrganizationJPanel", mainCompanyAssignmentPlacementPanel);
//            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//            layout.next(userProcessContainer);
//        }
        MainCompanyManufactureTaskAssignPanel mainCompanyManufactureTaskAssignPanel = new MainCompanyManufactureTaskAssignPanel(userProcessContainer, manufactureEnterprise);

        userProcessContainer.add("manageOrganizationJPanel", mainCompanyManufactureTaskAssignPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_assignmentjButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                userProcessContainer.add("manageOrganizationJPanel", new ManageLeaveOffJPanel(userProcessContainer, manufactureEnterprise));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CreateManufactureTaskJPanel createManufactureTask = new CreateManufactureTaskJPanel(userProcessContainer, manufactureEnterprise);
        userProcessContainer.add("buyingOrderCalculattionPanel", createManufactureTask);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignmentjButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable0;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel line1number;
    private javax.swing.JLabel line2number;
    private javax.swing.JLabel line3number;
    // End of variables declaration//GEN-END:variables
}
