/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerAssistantWorkArea;

import Business.Area.Area;
import Business.Employee.CustomerAssisatant;
import Business.Enterprise.ManufactureEnterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JPanel;

/**
 *
 * @author keweiji
 */
public class CustomerAssistantWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerAssistantWorkAreaJPanel
     */
      private JPanel userProcessContainer;
//      private Area area;
      private ArrayList<Area> areas;
      private UserAccount account;
//      private  CustomerAssistant customerAssistant;
      private CustomerAssisatant customerAssistant;
      private HashMap<ManufactureEnterprise,String> allManufactureEnterprises;
      
    public CustomerAssistantWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,ArrayList<Area> areas,HashMap<ManufactureEnterprise,String> allManufactureEnterprises) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.areas=areas;
        this.account = account;
        customerAssistant =(CustomerAssisatant) account.getEmployee();
        this.allManufactureEnterprises= allManufactureEnterprises;
        this.setOpaque(false);
//        System.out.println(this.areas.isEmpty());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageCustomerjButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageCustomerjButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        ManageCustomerjButton1.setText("Manage Customers");
        ManageCustomerjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCustomerjButton1ActionPerformed(evt);
            }
        });
        add(ManageCustomerjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 240, 60));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jButton2.setText("See My service History");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 240, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageCustomerjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCustomerjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add("manageOrganizationJPanel", new ManageCustomersJPanel(userProcessContainer, account, areas,allManufactureEnterprises));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_ManageCustomerjButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                    userProcessContainer.add("manageOrganizationJPanel", new HistoryPanel(userProcessContainer,customerAssistant));
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageCustomerjButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
