/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerServiceDirectorWorkArea;

import Business.Employee.CustomerAssisatant;
import Business.Employee.Employee;
import Business.Organization.CustomerServiceOrganization;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keweiji
 */
public class AnalysisPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalysisPanel
     */
    private JPanel userProcessContainer;
    private CustomerServiceOrganization customerServiceOrganization;

    public AnalysisPanel(JPanel userProcessContainer, CustomerServiceOrganization customerServiceOrganization) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerServiceOrganization = customerServiceOrganization;
        showtopthree();
        this.setOpaque(false);
    }

    public void showtopthree() {
        ArrayList<CustomerAssisatant> temp = new ArrayList<CustomerAssisatant>();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Employee employee : customerServiceOrganization.getEmployeeDirectory().getEmployeeList()) {
            if (employee instanceof CustomerAssisatant) {
                temp.add((CustomerAssisatant) employee);
            }
        }

        Collections.sort(temp, new Comparator<CustomerAssisatant>() {

            public int compare(CustomerAssisatant s1, CustomerAssisatant s2) {
                return s2.getServedcounts()-s1.getServedcounts() ;
                // Write your logic here.
            }
        });

        for (CustomerAssisatant customerAssisatant : temp) {
            Object[] row = new Object[2];
            row[0] = customerAssisatant.getName();
            row[1] = customerAssisatant.getServedcounts();
            model.addRow(row);
        }

//        Collections.sort(temp, c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Customer Assistanat", "Served Counts"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 520, 110));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("Top  assistants ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
