/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerServiceDirectorWorkArea;

import Business.Area.Area;
import Business.Employee.Customer;
import Business.Employee.Salesman;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SalesEnterprise;
import Business.Organization.SalesOrganization;
import Business.UserAccount.UserAccount;
//import Interface.SalesmanWorkarea._ManagementCustomers;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amber
 */
public class CreateNewCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewCustomer
     */
    private JPanel userProcessContainer;
//    private SalesOrganization organization;
    private SalesEnterprise salesEnterprise;
    
    private ArrayList<Area> areaList;
    public CreateNewCustomerJPanel(JPanel userProcessContainer, SalesEnterprise salesEnterprise ,ArrayList<Area> areaList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
//        this.organization = organization;
        this.salesEnterprise = salesEnterprise;
        this.areaList =areaList;
        populatebox();
        populatetable();
        this.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populatetable(){
        DefaultTableModel model =(DefaultTableModel)customertable.getModel();
        model.setRowCount(0);
        for(Customer customer:this.salesEnterprise.getCustomerDirectory().getCustomerDict()){
            Object[] row = new Object[2];
//            row[0]=customer.getId();
            row[0] = customer;
            row[1] = customer.getAddress();
            model.addRow(row);
        }
        
    }
    public void populatebox(){
        locationJComboBox.removeAllItems();
        
        for(Area area: this.areaList){
            locationJComboBox.addItem(area);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CustomerNameTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        BackjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customertable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        locationJComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Batang", 1, 36)); // NOI18N
        jLabel1.setText("Create New Customers");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Location:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, 20));

        CustomerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameTextFieldActionPerformed(evt);
            }
        });
        add(CustomerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 143, -1));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 140, 30));

        BackjButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        BackjButton.setText("<<Back");
        BackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButtonActionPerformed(evt);
            }
        });
        add(BackjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        customertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customertable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 510, 160));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        locationJComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        locationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(locationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameTextFieldActionPerformed
        // TODO add your handling code here:        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise);
      
    }//GEN-LAST:event_CustomerNameTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Area area = (Area)locationJComboBox.getSelectedItem();
        Customer c = this.salesEnterprise.getCustomerDirectory().addCustomer();
        area.getCustomerDirectory().getCustomerDict().add(c);
        c.setName(CustomerNameTextField.getText());
        c.setAddress(area.getName());
        CustomerNameTextField.setText("");
        JOptionPane.showMessageDialog(null, "customer successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);
        populatetable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackjButton;
    private javax.swing.JTextField CustomerNameTextField;
    private javax.swing.JTable customertable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox locationJComboBox;
    // End of variables declaration//GEN-END:variables
}
