/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerServiceDirectorWorkArea;

import Business.Area.Area;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SalesEnterprise;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author keweiji
 */
public class CustomerOrganizationDirectorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerOrganizationDirectorWorkAreaJPanel
     */
    private  ArrayList<Area> areaList;
    private JPanel userProcessContainer;
    private SalesEnterprise salesEnterprise;
    
    public CustomerOrganizationDirectorWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise,ArrayList<Area> areaList ) {
        initComponents();
        this.areaList=areaList;
        this.userProcessContainer=userProcessContainer;
        this.salesEnterprise = (SalesEnterprise)enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Add Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CreateNewCustomerJPanel createNewCustomerJPanel = new CreateNewCustomerJPanel(userProcessContainer, salesEnterprise, areaList);
        userProcessContainer.add("manageOrganizationJPanel", createNewCustomerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
