/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeliveryDirector;

import Business.Employee.Driver;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Entities.Buyorder;
import Business.Enterprise.Entities.DeliveryOrder;
import Business.Enterprise.Entities.SupplierWarehouse;
import Business.Enterprise.SupplierEnterprise;
import Business.Organization.DeliveryOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.DeliveryOrganization;
import Business.Organization.WarehouseOrganization;
import Business.UserAccount.UserAccount;
import Interface.WarehouseDirector.vieworders;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author amber
 */
public class SelectDriver extends javax.swing.JPanel {

    /**
     * Creates new form SelectDriver
     */
    JPanel containerJPanel;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    Buyorder buyorder;
    DeliveryOrder deliveryOrder;
    public SelectDriver(JPanel containerJPanel, UserAccount account, Organization organization, Enterprise enterprise, Buyorder buyorder) {
        initComponents();
        this.setOpaque(false);
        this.containerJPanel = containerJPanel;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.buyorder = buyorder;
        IDjLabel.setText(String.valueOf(this.buyorder.getOrderid()));
        EnterprisejLabel.setText(this.buyorder.getEnterprise().getName());
        DriverjComboBox.removeAllItems();
       for(Employee d : ((DeliveryOrganization)organization).getEmployeeDirectory().getEmployeeList()) {
           if(d.getRolenumber() == 12)
                DriverjComboBox.addItem(d);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IDjLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EnterprisejLabel = new javax.swing.JLabel();
        DriverjComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        SelectjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("Select Driver");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setText("OrderID:");

        IDjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        IDjLabel.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setText("Enterprise:");

        EnterprisejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        EnterprisejLabel.setText("jLabel3");

        DriverjComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        DriverjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setText("Driver:");

        SelectjButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        SelectjButton.setText("Select");
        SelectjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DriverjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(272, 272, 272))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnterprisejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDjLabel)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterprisejLabel)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DriverjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addComponent(SelectjButton)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SelectjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectjButtonActionPerformed
        // TODO add your handling code here:
        Driver d = ((Driver)DriverjComboBox.getSelectedItem());
        deliveryOrder = ((SupplierEnterprise)enterprise).getDeliveryOrderDictionary().AddDeliveryOrder();
        deliveryOrder.setBuyorder(buyorder);
        buyorder.setIsTakenBydriver(true);
        deliveryOrder.setDrivers(d);
        d.getDeliveryOrderDictionary().getDeliveryOrders().add(deliveryOrder);
       containerJPanel.remove(this);
        Component[] componentArray = containerJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SelectOrder selectOrder = (SelectOrder) component;
        selectOrder.populateTable();
        CardLayout layout = (CardLayout) containerJPanel.getLayout();
        layout.previous(containerJPanel);
    }//GEN-LAST:event_SelectjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DriverjComboBox;
    private javax.swing.JLabel EnterprisejLabel;
    private javax.swing.JLabel IDjLabel;
    private javax.swing.JButton SelectjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
