/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Driver;

import Business.Employee.Driver;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Entities.DeliveryOrder;
import Business.Enterprise.Entities.Material;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amber
 */
public class UpdateDelivery extends javax.swing.JPanel {

    /**
     * Creates new form UpdateDelivery
     */
    JPanel containerJPanel;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    public UpdateDelivery(JPanel containerJPanel, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.setOpaque(false);
        this.containerJPanel = containerJPanel;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LocationjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ReachjButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        LocationjComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(51, 51, 51));

        LocationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Location"
            }
        ));
        jScrollPane1.setViewportView(LocationjTable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel1.setText("Location:");

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ReachjButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ReachjButton.setText("Reach destination");
        ReachjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReachjButtonActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton3.setText("<<BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        LocationjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alaska", "Albany", "Annapolis", "Baton Rouge ", "Boston ", "Charleston", "Cheyenne", "Chicago", "Cincinati" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LocationjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ReachjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(463, 463, 463)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(ReachjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton3)
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ReachjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReachjButtonActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise = ((Driver)account.getEmployee()).getDeliveryOrder_ing().getBuyorder().getEnterprise();
         for(Material ma: ((Driver)account.getEmployee()).getDeliveryOrder_ing().getBuyorder().getMaterials().keySet()){
             if(enterprise.getWarehouse().getAvaliableMaterialHashMap().containsKey(ma)){
                  int oldquantity = enterprise.getWarehouse().getAvaliableMaterialHashMap().get(ma);
                  int newquantity = oldquantity + ((Driver)account.getEmployee()).getDeliveryOrder_ing().getBuyorder().getMaterials().get(ma);
                  enterprise.getWarehouse().getAvaliableMaterialHashMap().put(ma, newquantity);
             }else{

                 enterprise.getWarehouse().getAvaliableMaterialHashMap().put(ma, ((Driver)account.getEmployee()).getDeliveryOrder_ing().getBuyorder().getMaterials().get(ma));
             }

//             for(Material m : enterprise.getWarehouse().getAvaliableMaterialHashMap().keySet()){   
//             if(m.equals(ma)){
//                    int oldquantity = enterprise.getWarehouse().getAvaliableMaterialHashMap().get(m);
//                    int newquantity = oldquantity + ((Driver)account.getEmployee()).getDeliveryOrder_ing().getBuyorder().getMaterials().get(ma);
//                    enterprise.getWarehouse().getAvaliableMaterialHashMap().put(m, newquantity);
//                }
//            }
        }
         DeliveryOrder dDeliveryOrder = ((Driver)account.getEmployee()).getCompleted().AddDeliveryOrder();
         dDeliveryOrder = ((Driver)account.getEmployee()).getDeliveryOrder_ing();
         ((Driver)account.getEmployee()).setDeliveryOrder_ing(null);
        JOptionPane.showMessageDialog(null, "Material entering warehouse!");
    }//GEN-LAST:event_ReachjButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        containerJPanel.remove(this);
        CardLayout layout = (CardLayout)containerJPanel.getLayout();
        layout.previous(containerJPanel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String locationString = String.valueOf(LocationjComboBox.getSelectedItem());
        ((Driver)account.getEmployee()).getDeliveryOrder_ing().getLocation().add(locationString);
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) LocationjTable.getModel();

        model.setRowCount(0);
        if(((Driver)account.getEmployee()).getDeliveryOrder_ing()!=null){
                  for (String s : ((Driver)account.getEmployee()).getDeliveryOrder_ing().getLocation()) {
            Object[] row = new Object[3];
            row[0] = s;
            model.addRow(row);
        }
        }
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox LocationjComboBox;
    private javax.swing.JTable LocationjTable;
    private javax.swing.JButton ReachjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
